ansys/pyansys

- README.rst
- doc/source/index.rst
This PR adds a link to the Shared Components documentation.
There we have documented the OpenAPI-Common Library, and intend to also document any other shared components that the wider PyAnsys team generates.
> Add shared components documentation link

- README.rst
- doc/source/index.rst
This PR adds the new Granta MI BoM Analytics package to the PyAnsys landing page.
In future the `grantami.docs.pyansys.com` page will transition into a landing page that groups together all Granta MI PyAnsys packages. However, at the moment we only have one, and so we link to it directly.
Before this is merged, it will require a review from someone in the Granta organization.
> Add Granta MI BoM Analytics to landing page

- README.rst
Remove a rogue `s` in the text referring to the Shared Components
> Minor Text Fix

- README.rst
- doc/source/index.rst
@MaxJPRey 
This PR removes all the product-specific info from the README.rst file. I've saved a local copy of the original RST file so that I can check that the product-specific information that I removed exists already in the documentation for that library. In this PR, I've also changed tab names and order as per our email chat on Wednesday. Once I have write permission for the README.md fie for the PyAnsys account, I will clean it up.
> Remove product-specific sections and change organization

- README.rst
This much improves the landing page!
> Edits for better formatting. Also added links to PyPIM resources.

- pyproject.toml
> Python 3.11 is not supported by dependencies yet

- .github/workflows/ci-build.yml
As title says - Action does not accept GITHUB_TOKEN, but TOKEN
> Adapt to new arguments for docs publishing

- .github/workflows/ci-build.yml
- README.rst
As title says. Adding the badge as well.
> Adding pre-commit CI app

- README.rst
- doc/source/api.rst
- doc/source/examples.rst
- doc/source/index.rst
- doc/source/user_guide.rst
BoM Analytics docs have been migrated from https://grantami.docs.pyansys.com/ to https://bomanalytics.grantami.docs.pyansys.com/. This PR updates links in the PyAnsys docs to the new URL.
Currently both links are valid but we plan to serve higher level documentation for all Granta MI PyAnsys packages at https://grantami.docs.pyansys.com/.
> Update bomanalytics URL

- .github/workflows/ci-build.yml
- README.rst
- doc/source/getting_started.rst
- pyproject.toml
Dropping Python 3.7 from metapackage.
> FEAT: Dropping Python 3.7 support

- README.rst
> fix: missing references to PyMechanical in README

- .github/dependabot.yml
- doc/source/api.rst
- doc/source/examples.rst
- doc/source/index.rst
- doc/source/user_guide.rst
> cicd: dependabot group deps bump

- .github/workflows/ci-build.yml
- doc/source/conf.py
- add meilisearch index with dev and stable docs
> feat: add the meilisearch index

- doc/Makefile
- doc/make.bat
As title says. Action is already performing the linkcheck by default
> fix: remove linkcheck call in HTML build

- .github/workflows/create-milestone.yml
- README.rst
- doc/source/tools/libraries/index.rst
- pyproject.toml
- tools/links.py
As title says - pinging @greschd for visibility
> feat: add protoc helper

- pyproject.toml
Hi everyone,
not sure why it is still there, but users have reported PyDPF errors while installing via the pyansys package, and indeed since ansys-dpf-core 0.10.0 the dependency ansys-dpf-gate is not a dependency anymore and should even NOT be present, otherwise we have problems.
Is it possible to release a patch?
I'll have to check which versions are impacted.
Problem seen in:
[v2024.1.7](https://github.com/ansys/pyansys/releases/tag/v2024.1.7)
Starts with:
[v2024.1.0](https://github.com/ansys/pyansys/releases/tag/v2024.1.0)
So I guess a release of 2024.1.8 would be enough.
> Remove ansys-dpf-gate

- .github/workflows/create-milestone.yml
- pyproject.toml
- tools/links.py
Update PyGranta to 2024.2.0. This will need to be cherry-picked onto the 2024.2 release branch before release.
Also remove dependency on ansys-openapi-common, since in my opinion this is an unneeded constraint. I think currently only PyGranta packages include this, and if any other packages include it, they should declare it as a dependency themselves.
@klmcadams Adding you as a reviewer since you were suggested by GitHub.
> Update PyGranta to 2024.2.0

- pyproject.toml
ansys-fluent-core 0.21.1 does not exist, set the version to 0.21.0
> fix: ansys-fluent-core version

- .github/workflows/ci-build.yml
- README.rst
- doc/source/getting_started.rst
- doc/source/supported_versions.rst
- pyproject.toml
As title says. Following SPEC-0000 and our internal ADR - we should drop support for Python 3.9. This was informed in the dev meeting. We will reiterate this in a few weeks to the rest of the ecosystem.
> feat: dropping support for Python 3.9  and upgrade to v2025.1.dev0

- .gitignore
- doc/source/conf.py
- doc/source/index.rst
- doc/source/package_versions/.gitignore
- pyproject.toml
Closes #677 
Generated local docs can be found here: 
[local_build.zip](https://github.com/user-attachments/files/16960256/local_build.zip)
I would appreciate your feedback @ansys/pyansys-core - this was a request coming from ACE. @MaxJPRey is aware.
Screenshots: 
Index page
Example of package listing
Logic is not pretty, but effective. I had to go with the raw Jinja2 dependency because of issues with sphinx-jinja.
> feat: listing PyAnsys metapackage versions

- doc/source/conf.py
Closes #700
This should fix it (on a best effort basis)
> feat: pointing at the multiversion docs intelligently

- index.html
Ensures the `search.json` is fetched from the right location.
> fix: search.json location

- .pre-commit-config.yaml
- README.rst
- doc/source/conf.py
- pyproject.toml
- src/pyansys/__init__.py
- tools/catsitemap.py
- tools/links.py
- tools/milestone.py
This PR fixes [issue #746](https://github.com/ansys/pyansys/issues/746). The following files were edited for migration of linting/formatting within the ansys/pyansys repo to Ruff:
1. pyproject.toml
2. .pre-commit-config.yaml
3. README.rst
**I also trialed the current ruff configuration for pre-commit locally before submitting this pull request. The reviewer should check the re-formatted files to decide if we need to customize a couple of options prior to merging, or not.**
> feat: migrating linting/formatting exclusively to rust

- .github/workflows/update-gh-pages.yml
This pull request fix #752. It adds a scheduled cron to the update-gh-pages workflow. The interval is currently set to once every two weeks.
> feat: added cron job to update-gh-pages workflow

- README.rst
- projects.yaml
Proper name is PyDYNA. Changing PyDyna to use proper capitalization.
> PyDyna must be PyDYNA

- .github/workflows/ci-build.yml
- doc/source/api.rst
- doc/source/examples.rst
- doc/source/index.rst
- doc/source/user_guide.rst
- pyproject.toml
As title says. As per Ansys employee request
> feat: bump PyAEDT and PyEDB in 24R2 release

- pyproject.toml
Bump PyGranta to 2025 R1 release, for inclusion in the 2025.1 pyansys release.
> Bump PyGranta to 2025 R1 release

- doc/source/_static/js/landing_page.js
- doc/source/index.rst
Continuation of #796. 
It ensures that
> fix: filtering of families and tags

- pyproject.toml
Update PyACP from the release candidate to full release version.
Looking at the last dependabot run, I think this wouldn't update automatically. Maybe because the previous version was `0.1rc1`, not `0.1.0rc1`.
> Update PyACP to 0.1.0

- .github/workflows/ci-build.yml
This will close #809.
Not opening in draft mode so I can observe all ci runs.
> feat: use uv in ci

- projects.yaml
Pyedb examples have been migrated to the pyaedt-example repo, see https://examples.aedt.docs.pyansys.com/version/dev/examples/high_frequency/radiofrequency_mmwave/index.html
> fix(docs): pyedb examples URL

- .github/workflows/update-gh-pages.yml
Search results in the landing index page is not working. It is working with ansys actions and add all the bash commands here as well.
> ci(docs): update the search path and root url on landing index page
