.github/workflows/ci-build.yml, README.rst
Twine supports source dist linting.  Check rst can render for pypi.
=> add package linting

README.rst
Resolve #5 by changing the section header to have the correct ordering.
=> Fix sections

README.rst, doc/source/conf.py
Quick PR to update the README and add breadcrumbs.
=> add breadcrumbs and update readme

README.rst
Remove the MAPDL bullet points in the PyAEDT section.
=> Remove the MAPDL bullet points in the PyAEDT section.

doc/source/conf.py, requirements_docs.txt
Prepare for new release - change sphinx theme + reqs
=> Update reqs for new sphinx theme

README.rst, doc/source/index.rst
=> Add PyFluent

pyproject.toml
=> Adding ansys-fluent-visualization

pyproject.toml
Just formatting ``pyproject.toml``
=> Removing empty space + comment

.github/workflows/ci-build.yml, README.rst, doc/source/index.rst, doc/styles/Vocab/ANSYS/accept.txt
=> Adapting main README and docs

.github/workflows/ci-build.yml, .github/workflows/dependency-reviewer.yml
=> Allow permissive licenses only for PyAnsys packages

.github/dependabot.yml
Fix dependabot errors due to unable to find workflow files
=> Bug in actions update due to wrong config

pyproject.toml
=> Update versions for pyansys metapackage

.github/workflows/ci-build.yml, pyproject.toml
=> Supporting Python 3.10

pyproject.toml
=> Change Python limit

.github/workflows/ci-build.yml
=> Force extras-import stage to be finished before releasing

.github/workflows/ci-build.yml, .github/workflows/py311.yml, pyproject.toml
Provide support for Python 3.11 (experimental)
=> Accept Python 3.11 as an experimental stage

pyproject.toml
=> Adding ansys-dpf-gate as requirement

.github/workflows/ci-build.yml, .pre-commit-config.yaml, doc/Makefile, doc/make.bat, doc/source/conf.py, pyproject.toml
As title says. Also changing from poetry to flit =)
=> MAINT: moving to PyAnsys actions

README.rst, pyproject.toml
=> Adding ansys-seascape to the metapackage

.github/workflows/ci-build.yml
=> Fixing docs deployment

doc/source/conf.py
=> Fix broken link

.github/dependabot.yml
=> Increase PR limits for dependabot

README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst
=> Adding pyprimemesh

README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst, pyproject.toml
As title says. Coming from #144
=> Reorg and description issues with PyPrimeMesh

.github/workflows/create-milestone.yml, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst
=> Fixing PyTwin image and milestone inclusion for several projects

README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst
=> Changing fluent links

doc/source/conf.py
=> Missing path to docs edit button

doc/source/user_guide.rst
Links are broken so link to dev docs for now like APDL is doing.
=> Link to dev docs for now until stable links are working.

.github/workflows/create-milestone.yml, README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst, pyproject.toml
=> FEAT: Adding pysystem-coupling to metapackage

pyproject.toml
Adding 0.2b1 in preparation for PyAnsys metapackage release
=> MAINT: adding ansys-dpf-composites pre-release

pyproject.toml
=> MAINT: Bump version to 2024.1.dev0

doc/source/api.rst, doc/source/user_guide.rst
=> Update PyAnsys Math links

.github/workflows/ci-build.yml, .pre-commit-config.yaml, doc/source/getting_started.rst, doc/source/links.rst
Let's upload a list of all the dependencies installed depending on the OS and the Python version for the metapackage.
Pinging @koubaa for visibility. I think this will solve your problem without having to expand the scope of the ``pyproject.toml`` dependencies.
=> FEAT: uploading dependencies using ``pip freeze``

.github/workflows/ci-build.yml, README.rst, doc/source/conf.py, doc/source/getting_started.rst, doc/source/links.rst, pyproject.toml
=> fix: PyAnsys ref move

doc/source/conf.py
=> fix: broken links

.github/workflows/ci-build.yml, doc/Makefile, doc/make.bat, doc/source/api.rst, doc/source/conf.py, doc/source/examples.rst, doc/source/getting_started.rst, doc/source/index.rst, doc/source/user_guide.rst
=> feat: fix links and enable multi-version

README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst
=> fix: PyPIM links

pyproject.toml
Had to trigger it manually since we had asked dependabot to stop updating Sphinx.
7.2.0 is failing though...
=> feat: update Sphinx version to 7.2.2

.github/workflows/create-milestone.yml, README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst, pyproject.toml, tools/links.py
=> feat: adding PyDyna

.github/workflows/create-milestone.yml
Several typos. Enabling fail-fast: false
=> fix: milestone script

tools/milestone.py
=> feat: unpack any other values on tag for milestone

pyproject.toml
=> feat: update ansys-geometry-core

.github/workflows/ci-build.yml, pyproject.toml
=> fix: indexing dev docs by splitting the docs build stage.

.github/workflows/ci-build.yml, README.rst, doc/source/getting_started.rst, pyproject.toml, src/pyansys/__init__.py
=> feat: remove Python 3.8

.github/workflows/ci-build.yml, .github/workflows/update-gh-pages.yml
=> fix: force docs to point to dev docs

LICENSE
=> feat: update LICENSE

.flake8, .pre-commit-config.yaml, src/pyansys/__init__.py
=> feat: add license hook

.pre-commit-config.yaml
=> fix: pre-commit hook update

.github/workflows/create-milestone.yml, README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst, doc/styles/Vocab/ANSYS/accept.txt, pyproject.toml, tools/links.py
Removing Granta subpackages in favor of PyGranta metapackage
=> feat: change granta packages to pygranta metapackage

README.rst
=> fix: image PyAnsys

doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst
=> fix: spacing

.github/workflows/create-milestone.yml, README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst, pyproject.toml, tools/links.py
As title says. Related to https://github.com/ansys/pyacp/issues/473
=> feat: add PyACP

.github/workflows/update-gh-pages.yml
=> fix: landing page

pyproject.toml
=> fix: ansys-meshing-prime deleted version

.github/workflows/create-milestone.yml, README.rst, doc/source/api.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/user_guide.rst, pyproject.toml, tools/links.py
This pull-request adds PyWorkbench to the PyAnsys metapackage.
=> feat: add PyWorkbench

README.rst
=> fix: cleanup link PyModelcenter

doc/source/examples.rst
=> docs: adding reference to PyAnsys workflows examples

.github/workflows/update-gh-pages.yml, tools/catsitemap.py
This pull request fixes [issue 90](https://github.com/ansys-internal/pyansys-planning/issues/90). A script was added to automatically download sitemaps across all products, generate a sitemap of the sitemaps, and add generated files to the gh-pages branch of [ansys/pyansys](https://github.com/ansys/pyansys).
=> feat: added sitemap script to update-gh-pages.yml

pyproject.toml
Update the theme to fix the "This page" header in pages with no sections.
=> fix: documentation theme

projects.yaml
=> fix: additive URL

.github/workflows/update-gh-pages.yml, doc/source/_static/css/landing_page.css, doc/source/_static/js/landing_page.js, doc/source/_templates/landing_page_sidebar.html, doc/source/conf.py, doc/source/index.rst
This pull-request ensures that:
=> fix: cards are links now

.github/workflows/update-gh-pages.yml, doc/source/_templates/landing_page_sidebar.html
Finally, this is working. The variable substitution is performed now as expected.
=> fix: landing page action

projects.yaml
After @philipjusher's recommendation
=> docs: PyConceptEV belonging to Tools tag

.github/workflows/ci-build.yml
=> ci: allow referencing package temporarily due to licensing packaging issues

doc/source/_static/css/landing_page.css, doc/source/index.rst
=> docs: add tags to the cards

.pre-commit-config.yaml, doc/source/_static/css/landing_page.css, doc/source/_static/js/landing_page.js, doc/source/_templates/landing_page_sidebar.html
=> fix: add family count and align the styles for landing page

doc/source/tools/standalone/index.rst, doc/source/tools/toolkits/index.rst, projects.yaml
=> fix: landing page other tools images

.github/workflows/update-gh-pages.yml, doc/source/_static/js/landing_page.js
=> docs: fix landing page icon within js logic

projects.yaml
As title says - following the PyConceptEV last release
=> docs: fix conceptev examples link

projects.yaml
As the title. 
As requested in: https://github.com/ansys/pyansys/issues/824#issuecomment-2718571011
=> fix: update descriptions according to recommendations

pyproject.toml
=> build: using dev version for ansys-meshing-prime

doc/source/conf.py
Fix #1067 by addressing the issues found in the landing page.
=> fix(blog): static files
